name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install llvm 21
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 21
        rm llvm.sh
    - name: Fix llvm path
      run: |
        sudo ln -sf $(which llvm-ar-21) /usr/bin/llvm-ar
        sudo ln -sf $(which clang-21) /usr/bin/clang
    - name: Build
      run: make
    - name: Build with CFI enabled
      run: make clean && make CFI=unlabeled
